name: AstroDB

channels:
  - conda-forge

dependencies:
  - python
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - seaborn
  - jupyterlab
  - ipykernel
  - pip

  - pip:
      - ipypb
      - feautils
